// ============================================================
//  generate-fonts.js
//  Run ONCE to fetch all Google Fonts and build fonts-data.js
//
//  Usage:
//    node generate-fonts.js YOUR_GOOGLE_FONTS_API_KEY
//
//  After running, fonts-data.js is created and this script
//  plus your API key can be deleted forever.
// ============================================================

const https = require('https');
const fs    = require('fs');

const key = process.argv[2];
if (!key) {
  console.error('Usage: node generate-fonts.js YOUR_API_KEY');
  process.exit(1);
}

const TOP_PICKS = [
  'Montserrat', 'Playfair Display', 'Raleway', 'Lora',
  'Dancing Script', 'Josefin Sans', 'Bebas Neue',
  'Merriweather', 'Pacifico', 'Roboto Mono',
];

const url = `https://www.googleapis.com/webfonts/v1/webfonts?key=${key}&sort=popularity`;
console.log('Fetching Google Fonts API...');

https.get(url, (res) => {
  let raw = '';
  res.on('data', chunk => raw += chunk);
  res.on('end', () => {
    let data;
    try { data = JSON.parse(raw); } catch(e) {
      console.error('Failed to parse response:', raw.slice(0, 200));
      process.exit(1);
    }
    if (data.error) {
      console.error('API error:', data.error.message);
      process.exit(1);
    }

    const fonts = data.items.map((f, i) => ({
      name:      f.family,
      cat:       f.category,
      popularity: i,
      featured:  TOP_PICKS.includes(f.family),
    }));

    // Embed directly as a JS variable — no fetch() needed, works with file://
    const output = `// Auto-generated by generate-fonts.js — do not edit manually\n// ${fonts.length} fonts from Google Fonts, sorted by popularity\nconst FONTS = ${JSON.stringify(fonts, null, 2)};\n`;

    fs.writeFileSync('fonts-data.js', output, 'utf8');

    console.log(`✓ Done! ${fonts.length} fonts written to fonts-data.js`);
    console.log(`✓ Top picks: ${fonts.filter(f => f.featured).map(f => f.name).join(', ')}`);
    console.log('\nYou can now delete generate-fonts.js and your API key.');
    console.log('Open index.html directly — no server needed.');
  });
}).on('error', err => {
  console.error('Request failed:', err.message);
  process.exit(1);
});
