// ============================================================
//  scan-fonts.js
//  Run this whenever you add a new font to the /fonts/ folder.
//
//  Usage:
//    node scan-fonts.js
//
//  This scans the /fonts/ folder and writes fonts-manifest.js
//  so the app knows which custom fonts are available.
// ============================================================

const fs   = require('fs');
const path = require('path');

const FONTS_DIR    = path.join(__dirname, 'fonts');
const MANIFEST_OUT = path.join(__dirname, 'fonts-manifest.js');
const SUPPORTED    = ['.woff2', '.woff', '.ttf', '.otf'];

// Create fonts/ folder if it doesn't exist yet
if (!fs.existsSync(FONTS_DIR)) {
  fs.mkdirSync(FONTS_DIR);
  console.log('Created /fonts/ folder.');
}

const files = fs.readdirSync(FONTS_DIR).filter(f =>
  SUPPORTED.includes(path.extname(f).toLowerCase())
);

if (!files.length) {
  console.log('No font files found in /fonts/ — manifest will be empty.');
  console.log('Supported formats: .woff2, .woff, .ttf, .otf');
}

// Derive a readable font name from the filename
// e.g. "great_vibes.ttf" → "great vibes"
//      "GreatVibes-Regular.ttf" → "GreatVibes"
function toFontName(filename) {
  return path.basename(filename, path.extname(filename))
    .replace(/[-_](regular|bold|italic|light|medium|thin|black|semibold)/gi, '')
    .replace(/[-_]/g, ' ')
    .trim();
}

const fonts = files.map(file => ({
  name: toFontName(file),
  file: file,
}));

const output = `// Auto-generated by scan-fonts.js — do not edit manually\n// Run "node scan-fonts.js" after adding fonts to the /fonts/ folder\nconst CUSTOM_FONTS = ${JSON.stringify(fonts, null, 2)};\n`;

fs.writeFileSync(MANIFEST_OUT, output, 'utf8');

console.log(`✓ Done! ${fonts.length} font(s) found:`);
fonts.forEach(f => console.log(`  • ${f.name}  (${f.file})`));
console.log('\nReload index.html to see your custom fonts.');
