const fs = require('fs'), path = require('path');
const DIR = path.join(__dirname, 'fonts');
const OUT = path.join(__dirname, 'fonts-manifest.js');
const EXT = ['.woff2','.woff','.ttf','.otf'];
if (!fs.existsSync(DIR)) fs.mkdirSync(DIR);
const files = fs.readdirSync(DIR).filter(f => EXT.includes(path.extname(f).toLowerCase()));
const fonts = files.map(file => ({
  name: path.basename(file, path.extname(file)).replace(/[-_](regular|bold|italic|light|medium|thin|black|semibold)/gi,'').replace(/[-_]/g,' ').trim(),
  file
}));
fs.writeFileSync(OUT, `// Auto-generated by scan-fonts.js\nconst CUSTOM_FONTS = ${JSON.stringify(fonts, null, 2)};\n`);
console.log(`✓ ${fonts.length} font(s) found:`);
fonts.forEach(f => console.log(`  • ${f.name} (${f.file})`));
if (!fonts.length) console.log('  No fonts found. Add .ttf/.woff2 files to /fonts/');
